---
- name: Instalar y configurar Veyon
  hosts: localhost
  become: yes
  tasks:

    - name: Añadir repositorio Veyon
      apt_repository:
        repo: 'ppa:veyon/stable'
        state: present
        update_cache: yes

    - name: Instalar Veyon
      apt:
        name: veyon
        state: present

    - name: Copiar clave pública
      copy:
        src: teacher_public_key.pem
        dest: /etc/veyon/keys/public/teacher/key
        mode: '0644'

    - name: Importar clave
      command: veyon-cli authkeys import teacher public
