---
- name: Instalar y configurar Veyon
  hosts: localhost
  become: true
  tasks:
    - name: Instalar Veyon desde los repositorios oficiales
      apt:
        name: veyon
        state: present
        update_cache: yes

    - name: Crear directorio de clave pública si no existe
      file:
        path: /etc/veyon/keys/public/teacher
        state: directory
        mode: '0755'

    - name: Copiar clave pública
      copy:
        src: teacher_public_key.pem
        dest: /etc/veyon/keys/public/teacher/key
        mode: '0644'
